import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { categories } from "../../api/data";

export default function SlugCategory() {
  const router = useRouter();
  const { slug } = router.query;

  const currentCategory = categories.find((category) => category.id == slug);

  return (
    <>
      <Head >
      <title>{currentCategory.nombre} | Vesta USA</title>
      <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
      <section className="w-full bg-pink-200">
          <div
            className="seccion container flex flex-col items-center justify-center text-center align-middle lg:w-2/4"
            style={{ minHeight: "30vh" }}
          >
            <h1 className="text-center font-britanicaBold text-pink-600">
            Categoria: {currentCategory.nombre}
            </h1>
            <p className="text-center text-pink-600">
              Tener una tipografía con algo de impacto, pero con una elegancia
              visual, hará que tu arte suba al podio de los ganadores.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
