import Head from "next/head";
import { categories } from "../../api/data";
import {HeroBasic, CategoryItem} from "@/componentes";

export default function Categories() {
  return (
    <>
      <Head>
        <title>Categorias | Vesta USA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <HeroBasic
          title="Categorias"
          subtitle="Tener una tipografía con algo de impacto, pero con una elegancia visual, hará que tu arte suba al podio de los ganadores."
          textColor="text-pink-600"
          bgColor="bg-pink-200"
        />
        <section className="seccion container w-full py-24">
          <div id="grid-categories" className="grid grid-cols-4 gap-8">
            {categories.map((category) => (
              <CategoryItem category={category} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
