import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { productos } from "../api/data";
import { HeroBasic, ProductItem } from "@/componentes";

export default function Categories() {
  return (
    <>
      <Head>
        <title>Tienda | Vesta USA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <HeroBasic
          title="Explora nuestra tienda"
          subtitle="Tener una tipografía con algo de impacto, pero con una elegancia visual, hará que tu arte suba al podio de los ganadores."
          textColor="text-violet-800"
          bgColor="bg-violet-200"
        />
        <section className="seccion container w-full py-24">
          <div id="box" className="flex flex-row gap-9">
            <div className="w-1/5">
              <h3 className="font-britanicaBold">Filtros</h3>
            </div>
            <div
              id="grid-categories"
              className="grid flex-auto grid-cols-3 gap-8"
            >
              {productos.map((producto) => (
                <ProductItem producto={producto} />
              ))}
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
